# Generated by Django 5.0.6 on 2024-06-19 11:31

import magnit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0002_customuser_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_promotion',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, default=magnit.models.generate_unique_id, max_length=100, null=True, unique=True),
        ),
    ]
