# Generated by Django 5.0.6 on 2024-06-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0004_product_is_promotion_product_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
