# Generated by Django 5.0.6 on 2024-06-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loyalty_level',
            field=models.CharField(default='Bronze', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
