# Generated by Django 5.0.6 on 2024-06-19 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0007_rename_amount_spent_purchasehistory_loyalty_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='loyalty_level',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='loyalty_points',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnit.product'),
        ),
    ]
