# Generated by Django 5.0.6 on 2024-06-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0009_rename_loyaltypoints_loyaltypoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_promotion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_offer',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
