# Generated by Django 5.0.6 on 2024-06-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0011_product_is_promotion_product_special_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltylevel',
            old_name='minimum_points',
            new_name='required_points',
        ),
        migrations.RemoveField(
            model_name='loyaltylevel',
            name='point_percentage',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltylevel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnit.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
