# Generated by Django 5.0.6 on 2024-06-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0013_rename_required_points_loyaltylevel_point_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_price',
            new_name='price',
        ),
    ]
