# Generated by Django 5.0.6 on 2024-06-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0014_rename_total_price_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_promotion',
            new_name='promotions',
        ),
    ]
