# Generated by Django 5.0.6 on 2024-06-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0015_rename_is_promotion_product_promotions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='special_offer',
            new_name='special_offers',
        ),
    ]
