# Generated by Django 5.0.6 on 2024-06-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0016_rename_special_offer_product_special_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
    ]
