# Generated by Django 5.0.6 on 2024-06-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0017_remove_purchase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
    ]
