# Generated by Django 5.0.6 on 2024-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0018_remove_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
