# Generated by Django 5.0.6 on 2024-06-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0019_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_offers',
        ),
    ]
