# Generated by Django 5.0.6 on 2024-06-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0022_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
