# Generated by Django 5.0.6 on 2024-06-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnit', '0023_product_promotions_product_special_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
    ]
